import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Dashboard",
	description: "Generated by create next app",
};

export default function HelloWorld() {

    return (
        <div className="center">
            <div className="h-full w-full grid grid-rows-2 grid-cols-2 grid-flow-row gap-8 p-8">
                <div tabIndex={1} className="navbox">
                    <span>Lista książek</span>
                </div>
                <div tabIndex={2} className="navbox">
                    <span>Wypożycz</span>
                </div>
                <div tabIndex={3} className="navbox">
                    <span>Oddaj</span>
                </div>
                <div tabIndex={4} className="navbox">
                    <span>Dodaj</span>
                </div>
            </div>
        </div>
    );
}